### ISSUE TITLE
Menentukan Color Palette

### ISSUE THREAD

**Issue by mdaffailhami** [iTech-Hackathon/Task-Management#13]
# Saran Color Palette
Color Palette yang akan digunakan adalah Color Palettenya Material Design 2
Untuk lebih jelasnya bisa buka link berikut https://m2.material.io/design/color/the-color-system.html#color-theme-creation

## Contoh Material Design 2's Color Palette:
![Material Design 2's Color Palette](https://lh3.googleusercontent.com/k6WO1fd7T40A9JvSVfHqs0CPLFyTEDCecsVGxEDhOaTP0wUTPYOVVkxt60hKxBprgNoMqs8OyKqtlaQ4tDBtQJs-fTcZrpZEjxhUVQ=w1064-v0)

## List warna:
- Primary (Warna utama)
- On Primary (Warna komponen yang berada di atas warna Primary, misalnya seperti teks)
- Light Primary (Versi terangnya warna Primary)
- Dark Primary (Versi gelapnya warna Primary)
- Secondary (Warna kedua)
- On Secondary (Warna komponen yang berada di atas warna Secondary, misalnya seperti teks)
- Light Secondary (Versi terangnya warna Secondary)
- Dark Secondary (Versi gelapnya warna Secondary)
- Background (Warna background)
- On Background (Warna komponen yang berada di atas warna Background, misalnya seperti teks)
- Surface (Warna untuk komponen-komponen seperti card, sheet, dan menu.
- On Surface (Warna komponen yang berada di atas warna Surface, misalnya seperti teks)
- Error (Warna jika action gagal, misalnya ketika Project Manager gagal menambahkan Task karena database down)
- On Error (Warna komponen yang berada di atas warna Error, misalnya seperti teks)
- Success (Warna jika action sukes, misalnya ketika Project Manager berhasil menambahkan Task)
- On Succes (Warna komponen yang berada di atas warna Success, misalnya seperti teks)

## Komen dengan menggunakan format berikut:
| Color Name | Color Hex |
| - | - |
| Primary | \<hex> |
| On Primary | <hex(#FFFFFF, #000000)> |
| Light Primary | <hex, nullable> |
| Dark Primary | <hex, nullable> |
| Secondary | \<hex> |
| On Secondary | <hex(#FFFFFF, #000000)> |
| Light Secondary | <hex, nullable> |
| Dark Secondary | <hex, nullable> |
| Background | <hex, default = #FFFFFF> |
| On Background | <hex(#FFFFFF, #000000)> |
| Surface | <hex, default = #FFFFFF> |
| On Surface | <hex(#FFFFFF, #000000)> |
| Error | \<hex, default = #D32F2F> |
| On Error | <hex(#FFFFFF, #000000)> |
| Success | \<hex, default = #4CAF50> |
| On Success | <hex(#FFFFFF, #000000)> |

## Contoh:
| Color Name | Color Hex |
| - | - |
| Primary | #6200EE |
| On Primary | #FFFFFF
| Light Primary | null |
| Dark Primary | #3700B3 |
| Secondary | #03DAC6 |
| On Secondary | #000000 |
| Light Secondary | null |
| Dark Secondary | #018786 |
| Background | #FFFFFF |
| On Background | #000000 |
| Surface | #FFFFFF |
| On Surface | #000000 |
| Error | #D32F2F |
| On Error | #FFFFFF |
| Success | #4CAF50 |
| On Success | #FFFFFF |

**Comment by mdaffailhami** [comment]
Saran color palette untuk aplikasinya..

**Comment by afifabroory** [comment]
Saran Color Palatte, mengikuti Google Tasks.
![Google Tasks](https://user-images.githubusercontent.com/62495819/199630259-ff5cb71f-4578-4208-ab50-6674e56a7d7f.png)

Color Palatte yang digunakan:
![Google Tasks Collor Pallate](https://user-images.githubusercontent.com/62495819/199630189-1ef647a3-3a48-4398-878f-9ee431db00a1.png)

**Comment by afifabroory** [comment]
Selebihnya gimana? Possible aja kah? Wydt @ArryPutra  @mdaffailhami @bhaktiramadhanii

**Comment by mdaffailhami** [comment]
Saran:
Indigo (Primary) & Orange (Secondary)
![Screenshot from 2022-11-03 14-43-15](https://user-images.githubusercontent.com/74972129/199661117-5bc1151a-b3e3-4b5a-8e1d-7ccce079e98f.png)
| Color Name | Color Hex |
| - | - |
| Primary | #303F9F |
| On Primary | #FFFFFF |
| Light Primary | null |
| Dark Primary | null |
| Secondary | #F57C00 |
| On Secondary | #FFFFFF |
| Light Secondary | null |
| Dark Secondary | null |
| Background | #FFFFFF |
| On Background | #000000 |
| Surface | #FFFFFF |
| On Surface | #000000 |
| Error | #D32F2F |
| On Error | #FFFFFF |
| Success | #4CAF50 |
| On Success | #FFFFFF |

**Comment by mdaffailhami** [comment]
| Color Name | Color Hex |
| - | - |
| Primary | #1D60D1 |
| On Primary | #FFFFFF |
| Light Primary | #E2EBFA |
| Dark Primary | #0B5DEB |
| Secondary | #000000 |
| On Secondary | #FFFFFF |
| Light Secondary | null |
| Dark Secondary | null |
| Background | #FFFFFF |
| On Background | #000000 |
| Surface | #FFFFFF |
| On Surface | #000000 |
| Error | #D32F2F |
| On Error | #FFFFFF |
| Success | #4CAF50 |
| On Success | #FFFFFF |

Inspiration: https://dribbble.com/shots/19752197-Task-Management-App

**Comment by mdaffailhami** [comment]
![Colors](https://user-images.githubusercontent.com/74972129/200205415-9735a429-f850-4146-9196-20ba02e603d4.png)
| Color Name | Color Hex |
| - | - |
| Primary | #1976D2 |
| On Primary | #FFFFFF |
| Light Primary | #1E88E5 |
| Dark Primary | #1565C0 |
| Secondary | #757575 |
| On Secondary | #FFFFFF |
| Light Secondary | #BDBDBD |
| Dark Secondary | #424242 |
| Background | #FFFFFF |
| On Background | #000000 |
| Surface | #FFFFFF |
| On Surface | #000000 |
| Error | #D32F2F |
| On Error | #FFFFFF |
| Success | #2E7D32 |
| On Success | #FFFFFF |
