### ISSUE TITLE
Membuat organisasi file

### ISSUE THREAD

**Issue by afifabroory** [iTech-Hackathon/Task-Management#25]

**Comment by bhaktiramadhani** [comment]
### Organisasi file

**Di dalam folder src terdapat beberapa folder yaitu:**
- assets
  berisi file-file assets yang akan digunakan nanti contohnya seperti image, logo DLL
- pages
  berisi file-file yang akan digunakan untuk membuat page-page
- components
  berisi file-file component-component

**Comment by afifabroory** [comment]
Nice!
> ### Organisasi file
> ...
>   berisi file-file component-component
