### ISSUE TITLE
List library yang diperlukan

### ISSUE THREAD

**Issue by afifabroory** [iTech-Hackathon/Task-Management#4]
List library yang diperlukan untuk project. Dengan menggunakan format:
```
- _Nama library_
  Tujuan: _Tujuan library_
  Versi: _versi yang akan digunakan_
  Lisensi: _lisensi yang akan digunakan_
  URL: _URL website library_
```

Sebagai contoh:
- Abcd
  Tujuan: Markdown  support
  Versi: 0.1.0
  Lisensi: MIT
  URL: https://example.com

**Notes:**
- List dependencies yang akan digunakan dengan comment issue/task ini.
- Utamakan library dengan lisensi non GPL
- Pastikan library yg akan digunakan memenuhi kebutuhan dan spesifikasi project.

**Comment by mdaffailhami** [comment]
**`npm install @mui/material @emotion/react @emotion/styled`**

- @mui/material
Tujuan: Material Design UI
Versi: 5.10.12
Lisensi: MIT
URL: https://www.npmjs.com/package/@mui/material

- @emotion/react
Tujuan: Sepaket dengan @mui/material
Versi: 11.10.5
Lisensi: MIT
URL: https://www.npmjs.com/package/@emotion/react

- @emotion/styled
Tujuan: Sepaket dengan @mui/material
Versi: 11.10.5
Lisensi: MIT
URL: https://www.npmjs.com/package/@emotion/styled

**Comment by afifabroory** [comment]
Sip. Kalau library readme parser & rendering engine? @mdaffailhami @bhaktiramadhanii 

Sepertinya butuh library yg lightweight supaya nggak memberatkan sisi user.

> **`npm install @mui/material @emotion/react @emotion/styled`**
> ...
>   URL: https://www.npmjs.com/package/@emotion/styled

**Comment by mdaffailhami** [comment]
> Sip. Kalau library readme parser & rendering engine? @mdaffailhami @bhaktiramadhanii
> 
> Sepertinya butuh library yg lightweight supaya nggak memberatkan sisi user.

**`npm install marked`**
- marked
  Tujuan: Ngeparsing Markdown menjadi HTML
  Versi: 4.1.1
  Lisensi: MIT
  URL: https://www.npmjs.com/package/marked

**Comment by afifabroory** [comment]
`npm i firebase`

- Firebase
  Tujuan: SDK untuk menghubungkan aplikasi dengan backend.
  Versi: 9.13.0
  Lisensi: Apache-2.0
  URL: https://firebase.google.com/

**Comment by afifabroory** [comment]
Silahkeun tambahkan dependency yg kurang, ngikutin format yg ada @bhaktiramadhanii

**Comment by bhaktiramadhani** [comment]
`npm install react-router-dom`

- React Router
   Tujuan: Untuk Me manage Pages
   Versi: 6.4.3
   Mit
   URL: [https://reactrouter.com/en/main](url)

**Comment by mdaffailhami** [comment]
**`npm install @fontsource/roboto @mui/icons-material`**

- @fontsource/roboto
  Tujuan: Mengubah font utama menjadi Roboto (Material Design Font)
  Versi: 4.5.8
  Lisensi: MIT
  URL: https://www.npmjs.com/package/@fontsource/roboto

- @mui/icons-material
  Tujuan: Mendapatkan berbagai icons material
  Versi: 5.10.9
  Lisensi: MIT
  URL: https://www.npmjs.com/package/@mui/icons-material
